### ISSUE TITLE
Select Component hardcoded minimum of 5 options

### ISSUE THREAD

**Issue by trevorplant** [LeadcodeDev/commander#1]
When calculating the start and end position for rendering the minimum number of options is hardcoded to 5. By using the number of options as the limit the select component will be able to render any number of options. ie: 
instead of
```
 int start = currentIndex - 2 >= 0 ? currentIndex - 2 : 0;
      if (currentIndex >= filteredArr.length - 2) {
        start = filteredArr.length - 5;
      }
      int end = start + 5 <= filteredArr.length ? start + 5 : filteredArr.length;
```
replace the hardcoded 5 with
```
int start = currentIndex - 2 >= 0 ? currentIndex - 2 : 0;
      if (currentIndex >= filteredArr.length - 2) {
        start = filteredArr.length - options.length;
      }
      int end = start + options.length <= filteredArr.length
          ? start +options.length
          : filteredArr.length;
```

**Comment by LeadcodeDev** [comment]
Hello @trevorplant, thank you very much for your feedback, I've made some changes to the select component to incorporate your request while fixing a bug that was causing a `throw`.
I also took the opportunity to improve the readme, which was a bit old 👀

Now you can use the new release : `commander_ui: 1.3.0`

Thanks again and I look forward to seeing you 🙂
